global:
  scrape_interval:      15s #Set the scrape interval to every 15s. Default is 1m
  evaluation_interval:  15s #Evaluate rules every 15s. The default is every 1m
  #scrape_timeout is set to the global default (10s)

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's prometheus itself:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'pwned'
    static_configs:
      - targets: ['go-pwned:2112']